#ifndef CONSTANTS_H
#define CONSTANTS_H

//Colores
#define GREEN_H QString("#32AF32")
#define SOFT_RED_H QString("#FF2828")

//LEGACY - EXPERT1
#define TIRION_FORDRING "EX1_383"
#define CENARIUS "EX1_573"
//NAXX
#define LOATHEB "FP1_030"
//LOE
#define RENO_JACKSON "LOE_011"
#define SIR_FINLEY_MRRGGLTON "LOE_076"
#define BRANN_BRONZEBEARD "LOE_077"
#define ELISE_STARSEEKER "LOE_079"
//OG
#define YSHAARJ_RAGE_UNBOUND "OG_042"
#define NZOTH_THE_CORRUPTOR "OG_133"
#define YOGG_SARON_HOPES_END "OG_134"
#define CTHUN "OG_280"
//GANGS
#define KAZAKUS "CFM_621"
#define PATCHES_THE_PIRATE "CFM_637"
#define DON_HANCHO "CFM_685"
#define AYA_BLACKPAW "CFM_902"
//THE_SUNKEN_CITY
#define SEAFLOOR_GATEWAY "TSC_055"
//BATTLE_OF_THE_BANDS
#define MC_BLINGTRON "ETC_078"
#define VOID_VIRTUOSO "ETC_081"
#define COWBELL_SOLOIST "ETC_101"
#define HIPSTER "ETC_103"
#define ROCK_MASTER_VOONE "ETC_121"
#define KANGOR_DANCING_KING "ETC_329"
#define HEARTTHROB "ETC_339"
#define INZAH "ETC_371"
#define ZOK_FOGSNOUT "ETC_386"
#define DJ_MANASTORM "ETC_395"
#define THE_ONE_AMALGAM_BAND "ETC_409"
#define SNAKEBITE "ETC_410"
#define CAGE_HEAD "ETC_526"
#define TONY_KING_OF_PIRACY "ETC_541"
#define MISTER_MUKLA "ETC_836"
//TITANS
#define SIF "TTN_071"
#define IMPRISONED_HORROR "TTN_462"
#define MINOTAUREN "TTN_466"
#define RADEN "TTN_481"
#define LOKEN_JAILER_OF_YOGGSARON "TTN_487"
#define ANGRY_HELHOUND "TTN_713"
#define HODIR_FATHER_OF_GIANTS "TTN_752"
#define RAVENOUS_KRAKEN "TTN_754"
#define ODYN_PRIME_DESIGNATE "TTN_811"
#define THORIM_STORMLORD "TTN_835"
#define JOTUN_THE_ETERNAL "TTN_842"
#define TYR "TTN_857"
#define ASTRAL_SERPENT "TTN_907"
#define MIMIRON_THE_MASTERMIND "TTN_920"
#define FREYA_KEEPER_OF_NATURE "TTN_940"
//WONDERS
#define CTHUN2 "WON_135"
#define AYA_BLACKPAW2 "WON_136"
#define DON_HANCHO2 "WON_137"
//WILD_WEST
#define KOBOLD_MINER "WW_001"
#define SKARR_THE_CATASTROPHE "WW_026"
#define POPGAR_THE_PUTRID "WW_091"
#define PILE_OF_BONES "WW_324"
#define HOWDYFIN "WW_333"
#define SPIRIT_OF_THE_BADLANDS "WW_337"
#define SHERIFF_BARRELBRIM "WW_359"
#define RESKA_THE_PIT_BOSS "WW_373"
#define SLAGMAW_THE_SLUMBERING "WW_375"
#define WALKING_MOUNTAIN "WW_382"
#define PIP_THE_POTENT "WW_394"
#define HIGH_NOON_DUELIST "WW_399"
#define GUNSLINGER_KURTRUS "WW_401"
#define WISHING_WELL "WW_415"
#define DRILLY_THE_KID "WW_417"
#define TAETHELAN_BLOODWATCHER "WW_430"
#define THELDURIN_THE_LOST "WW_815"
#define FYE_THE_SETTING_SUN "WW_825"
//ISLAND_VACATION
#define TURBULUS "WORK_013"
#define PORTALMANCER_SKYLA "WORK_063"

#endif // CONSTANTS_H
